from dataclasses import dataclass
from typing import List, Literal

# ========= Types =========

FrontendSkillLevel = Literal["foundational", "intermediate", "advanced"]


@dataclass(frozen=True)
class FrontendSkill:
    """
    Canonical frontend skill definition.

    Purpose:
    - Used for interview calibration and skill selection logic
    - NOT shown to users
    - NOT generated by LLMs
    """
    id: str
    label: str
    level: FrontendSkillLevel
    description: str
    importance: int          # 1–5 (used for weighted selection)
    interview_safe: bool     # allowed as Q1 skill

FRONTEND_SKILL_MAP: List[FrontendSkill] = [
    # ========== FOUNDATIONAL ==========
    # High-signal, interview-safe for Q1
    FrontendSkill(
        id="js_fundamentals",
        label="JavaScript Fundamentals",
        level="foundational",
        description=(
            "Core JavaScript concepts such as variables, scope, closures, "
            "and execution context."
        ),
        importance=5,
        interview_safe=True,
    ),
    FrontendSkill(
        id="browser_rendering",
        label="Browser Rendering & DOM",
        level="foundational",
        description=(
            "How browsers parse HTML/CSS, build the DOM/CSSOM, "
            "and render pages."
        ),
        importance=5,
        interview_safe=True,
    ),
    FrontendSkill(
        id="html_css_basics",
        label="HTML & CSS Basics",
        level="foundational",
        description=(
            "Semantic HTML, CSS layout basics, and how styles affect rendering."
        ),
        importance=4,
        interview_safe=True,
    ),

    # ========== INTERMEDIATE ==========
    # Used only if experience allows
    FrontendSkill(
        id="js_execution_model",
        label="JavaScript Execution Model",
        level="intermediate",
        description=(
            "Call stack, event loop, microtasks, macrotasks, "
            "and async behavior."
        ),
        importance=4,
        interview_safe=True,
    ),
    FrontendSkill(
        id="react_rendering_basics",
        label="React Rendering Basics",
        level="intermediate",
        description=(
            "Component rendering, reconciliation, and state-driven updates."
        ),
        importance=4,
        interview_safe=True,
    ),
    FrontendSkill(
        id="frontend_performance_basics",
        label="Frontend Performance Basics",
        level="intermediate",
        description=(
            "Bundle size, rendering performance, and basic optimization strategies."
        ),
        importance=3,
        interview_safe=True,
    ),

    # ========== ADVANCED ==========
    FrontendSkill(
        id="rendering_optimizations",
        label="Rendering Optimizations",
        level="advanced",
        description=(
            "Advanced rendering strategies, memoization, "
            "and performance tuning."
        ),
        importance=3,
        interview_safe=False,
    ),
    FrontendSkill(
        id="memory_management",
        label="Memory Management & Leaks",
        level="advanced",
        description=(
            "Memory profiling, garbage collection behavior, "
            "and leak prevention."
        ),
        importance=2,
        interview_safe=False,
    ),
]
