from pydantic import BaseModel, Field, HttpUrl
from typing import List, Optional
from datetime import datetime
from enum import Enum


class ResourceType(str, Enum):
    """Valid resource types"""

    BLOG = "blog"
    VIDEO = "video"
    ARTICLE = "article"
    COURSE = "course"
    DOCUMENTATION = "documentation"
    TUTORIAL = "tutorial"


class ResourceDocument(BaseModel):
    """
    Firestore document schema for learning resources.
    This is the source of truth for all verified resources.
    """

    id: Optional[str] = Field(None, description="Firestore document ID")
    url: str = Field(..., description="Resource URL")
    title: str = Field(..., description="Resource title")
    type: ResourceType = Field(..., description="Type of resource")
    tags: List[str] = Field(
        default_factory=list,
        description="Topics/tags for categorization (e.g., ['javascript', 'loops'])",
    )
    summary: Optional[str] = Field(
        None, description="LLM-generated summary (populated by ingestion service)"
    )
    is_embedded: bool = Field(
        default=False, description="Whether this resource has been embedded in ChromaDB"
    )
    created_at: Optional[datetime] = Field(
        default=None, description="Timestamp when resource was created"
    )
    updated_at: Optional[datetime] = Field(
        default=None, description="Timestamp when resource was last updated"
    )


class CreateResourceRequest(BaseModel):
    """Request body for creating a new resource"""

    url: str = Field(..., description="Resource URL")
    title: str = Field(..., description="Resource title")
    type: ResourceType = Field(..., description="Type of resource")
    tags: List[str] = Field(
        default_factory=list, description="Topics/tags for categorization"
    )
    summary: Optional[str] = Field(
        None,
        description="Optional manual summary (otherwise generated by ingestion service)",
    )


class UpdateResourceRequest(BaseModel):
    """Request body for updating a resource (all fields optional)"""

    url: Optional[str] = Field(None, description="Resource URL")
    title: Optional[str] = Field(None, description="Resource title")
    type: Optional[ResourceType] = Field(None, description="Type of resource")
    tags: Optional[List[str]] = Field(
        None, description="Topics/tags for categorization"
    )
    summary: Optional[str] = Field(None, description="Resource summary")


class ResourceResponse(BaseModel):
    """API response for a single resource"""

    id: str
    url: str
    title: str
    type: ResourceType
    tags: List[str]
    summary: Optional[str]
    is_embedded: bool
    created_at: datetime
    updated_at: datetime


class ResourceListResponse(BaseModel):
    """API response for listing resources"""

    resources: List[ResourceResponse]
    total: int = Field(..., description="Total number of resources matching filters")
